#ifndef _FLASH_TOOL_ERROR_CODE_DEF_H
#define _FLASH_TOOL_ERROR_CODE_DEF_H
typedef enum {
	//<8000 is defined by brom.dll mtk_status.h
	FT_SUCCESS = 8000,
	FT_EXCEPTION = 8001,
	FT_USER_PRESS_STOP_BUTTON = 8002,
	//SCAN USB ERROR
	FT_FIND_USB_ERROR = 8100,
	FT_FIND_GADGET_USB_ERROR = 8101,
	//PLATFORM ERROR
	FT_DL_PLATFORM_ERROR = 8200,
	//BACKUP->FORMAT->DL->RESTORE ERROR
	FT_UPGRADE_FOLDER_OVERLAPPED = 8300,
	FT_UPGRADE_FOLDER_NOT_EXSIT = 8301,
	FT_UPGRADE_DIR_CREATE_FAIL = 8302,
	FT_UPGRADE_FILE_CORRUPTED = 8303,
       FT_UPGRADE_FILE_NOT_EXSIT = 8304,
	FT_UPGRADE_BACKUP_ROM_NOT_EXSIT = 8305,
	FT_OTP_FILE_NOT_WORD_ALIGN = 8306,
	FT_UPGRADE_LAYOUT_CHANGED = 8037,
	FT_DOWNLOAD_LAYOUT_CHANGED = 8038,
	FT_FILE_FOLDER_IS_NOT_EXIST = 8039,
	FT_FILE_IS_NOT_EXIT = 8040,
	FT_CHECKSUM_NOT_MATCH = 8041,
	FT_CREATE_FILE_FAIL = 8042,
	FT_STORAGE_ERROR = 8043,
	FT_SCI_DOWNLOAD_LAYOUT_CHANGE = 8044,
	FT_UPGRADE_GET_PMT_FAIL = 8045,
	FT_UPGRADE_BACKUP_SIZE_CHANGE = 8046,
	FT_UPGRADE_NOT_SUPPORT_ROM_TYPE = 8047
} FLASH_TOOL_RESULT;
#endif //_FLASH_TOOL_ERROR_CODE_DEF_H
